### ISSUE TITLE
Site Refresh Master Issue

### ISSUE THREAD

**Issue by jonthegeek** [rfordatascience/r4dswebsite#62]
I would like to completely redesign the site to make it more functional! In this issue I'll sort out the overall design.

Jobs the site has:

- [x] Help people trust R4DS.
- [x] Make it easy for new learners to find help.
- [x] Allow learners to keep learning.
- [x] Recruit mentors.

Parse those out into their own tickets.
